# Generated by Django 5.1.5 on 2025-08-21 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Numéro de téléphone sénégalais invalide (ex: +221769001942)",
                        regex="^\\+221[0-9]{9}$",
                    )
                ],
                verbose_name="Téléphone",
            ),
        ),
    ]
