# Generated by Django 5.2.5 on 2025-08-21 20:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="Début de période")),
                ("period_end", models.DateField(verbose_name="Fin de période")),
                (
                    "total_orders",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total des commandes"
                    ),
                ),
                (
                    "pending_orders",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Commandes en attente"
                    ),
                ),
                (
                    "completed_orders",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Commandes terminées"
                    ),
                ),
                (
                    "cancelled_orders",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Commandes annulées"
                    ),
                ),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Chiffre d'affaires total",
                    ),
                ),
                (
                    "total_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total payé",
                    ),
                ),
                (
                    "total_outstanding",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total restant dû",
                    ),
                ),
                (
                    "total_customers",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total des clients"
                    ),
                ),
                (
                    "new_customers",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nouveaux clients"
                    ),
                ),
                (
                    "active_customers",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Clients actifs"
                    ),
                ),
                (
                    "total_products",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total des produits"
                    ),
                ),
                (
                    "low_stock_products",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Produits en stock faible"
                    ),
                ),
                (
                    "out_of_stock_products",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Produits en rupture"
                    ),
                ),
                (
                    "last_calculated",
                    models.DateTimeField(auto_now=True, verbose_name="Dernier calcul"),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=True, verbose_name="Métriques actuelles"
                    ),
                ),
            ],
            options={
                "verbose_name": "Métrique du tableau de bord",
                "verbose_name_plural": "Métriques du tableau de bord",
                "ordering": ["-period_start"],
                "unique_together": {("period_start", "period_end")},
            },
        ),
        migrations.CreateModel(
            name="TopCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_orders",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total des commandes"
                    ),
                ),
                (
                    "total_spent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total dépensé",
                    ),
                ),
                (
                    "last_order_date",
                    models.DateField(verbose_name="Date de dernière commande"),
                ),
                ("rank", models.PositiveIntegerField(verbose_name="Rang")),
                ("period_start", models.DateField(verbose_name="Début de période")),
                ("period_end", models.DateField(verbose_name="Fin de période")),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                        verbose_name="Client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meilleur client",
                "verbose_name_plural": "Meilleurs clients",
                "ordering": ["rank"],
                "unique_together": {("customer", "period_start", "period_end")},
            },
        ),
        migrations.CreateModel(
            name="TopProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Quantité totale vendue"
                    ),
                ),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Revenus totaux",
                    ),
                ),
                (
                    "total_orders",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de commandes"
                    ),
                ),
                ("rank", models.PositiveIntegerField(verbose_name="Rang")),
                ("period_start", models.DateField(verbose_name="Début de période")),
                ("period_end", models.DateField(verbose_name="Fin de période")),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                        verbose_name="Produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meilleur produit",
                "verbose_name_plural": "Meilleurs produits",
                "ordering": ["rank"],
                "unique_together": {("product", "period_start", "period_end")},
            },
        ),
    ]
